name = "TaylorDev"
uuid = "911e41e3-ee0b-4f9a-9ab7-3a6bcaf6fbd2"
authors = ["Alseïdon"]
version = "1.0.0-DEV"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
